/**
 * Seed documents for top 20 Swiss municipalities.
 *
 * Downloads real protocol PDFs from municipality websites,
 * uploads to Vercel Blob, generates page images, and
 * inserts document + page records.
 *
 * Usage:
 *   pnpm db:seed-top20              # full run (download + upload + insert)
 *   pnpm db:seed-top20 -- --dry-run # just log what would be done
 *   pnpm db:seed-top20 -- --metadata-only # insert DB records without blob upload
 */

import { config } from "dotenv";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dir = dirname(fileURLToPath(import.meta.url));
config({ path: resolve(__dir, "../../../.env.local") });

import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import { eq, ilike } from "drizzle-orm";
import { put } from "@vercel/blob";
import {
  municipalities,
  documents,
  documentPages,
  type NewDocument,
  type NewDocumentPage,
} from "../src/schema/index";

// ─── Top 20 municipality protocol data ───
// Each entry contains the municipality name, protocol page URLs,
// and known direct PDF links from their official websites.

interface ProtocolEntry {
  municipalityName: string;
  canton: string;
  protocolPageUrl: string;
  pdfs: Array<{
    title: string;
    sourceUrl: string;
    sessionDate: string; // ISO date
    type: "protocol" | "other";
  }>;
}

const TOP_20: ProtocolEntry[] = [
  {
    municipalityName: "Zürich",
    canton: "ZH",
    protocolPageUrl: "https://www.gemeinderat-zuerich.ch/sitzungen/termine/",
    pdfs: [
      {
        title: "Budget 2025 – Beschluss des Gemeinderats vom 12. Dezember 2024",
        sourceUrl: "https://www.stadt-zuerich.ch/content/dam/web/de/aktuell/publikationen/2024/budget/budget-2025-beschluss-gemeinderat.pdf",
        sessionDate: "2024-12-12",
        type: "protocol",
      },
      {
        title: "Globalbudgets 2025 – Beschluss des Gemeinderats",
        sourceUrl: "https://www.stadt-zuerich.ch/content/dam/web/de/aktuell/publikationen/2024/budget/globalbudgets-2025-beschluss-gemeinderat.pdf",
        sessionDate: "2024-12-12",
        type: "protocol",
      },
    ],
  },
  {
    municipalityName: "Genève",
    canton: "GE",
    protocolPageUrl: "https://www.geneve.ch/autorites-administration/conseil-municipal/seances-plenieres",
    pdfs: [
      {
        title: "Procès-verbal du Conseil municipal de Genève, 4 février 2025",
        sourceUrl: "https://www.geneve.ch/sites/default/files/filecm/CM/sessions/2025-02-04/PV/PV-session-CM-geneve-2025-02-04.pdf",
        sessionDate: "2025-02-04",
        type: "protocol",
      },
    ],
  },
  {
    municipalityName: "Basel",
    canton: "BS",
    protocolPageUrl: "https://grosserrat.bs.ch/ratsbetrieb/ratsprotokolle",
    pdfs: [
      {
        title: "Vollprotokoll Grosser Rat Basel-Stadt, 9. September 2020",
        sourceUrl: "https://grosserrat.bs.ch/media/files/ratsprotokolle/vollprotokoll_2020-09-09.pdf",
        sessionDate: "2020-09-09",
        type: "protocol",
      },
    ],
  },
  {
    municipalityName: "Lausanne",
    canton: "VD",
    protocolPageUrl: "https://www.lausanne.ch/officiel/conseil-communal/seances.html",
    pdfs: [
      {
        title: "Bulletin du Conseil communal – Séance No 17 du 26 mars 2024",
        sourceUrl: "https://www.lausanne.ch/.binaryData/website/path/lausanne/officiel/conseil-communal/bulletins/bulletins-2024/contentAutogenerated/autogeneratedContainer/col1/02/linkList/014/websitedownload/D%C3%A9bats_17_I_26.03.2024_Carrel.2024-08-19-11-25-00.pdf",
        sessionDate: "2024-03-26",
        type: "protocol",
      },
    ],
  },
  {
    municipalityName: "Bern",
    canton: "BE",
    protocolPageUrl: "https://www.bern.ch/politik-und-verwaltung/stadtrat/sitzung-geschaeft",
    pdfs: [
      {
        title: "Stadtratsprotokoll Nr. 13 vom 10.09.2020",
        sourceUrl: "https://www.bern.ch/politik-und-verwaltung/stadtrat/ratsversand/stadtratsprotokoll-nr-13-vom-10.09.2020",
        sessionDate: "2020-09-10",
        type: "protocol",
      },
    ],
  },
  {
    municipalityName: "Winterthur",
    canton: "ZH",
    protocolPageUrl: "https://gemeinderat.winterthur.ch/",
    pdfs: [
      {
        title: "Stadtrat Protokollauszug – Konstituierungsbeschluss, 22.01.2025",
        sourceUrl: "https://stadt.winterthur.ch/stadtratsbeschluesse/beschluesse-des-stadtrats/stadtratssitzung-vom-22-januar-2025/stadtratssitzung-vom-22-januar-2025/konstituierungsbeschluss-2-anpassungen.pdf/@@download/file/Konstituierungsbeschluss%202;%20Anpassungen.pdf",
        sessionDate: "2025-01-22",
        type: "protocol",
      },
    ],
  },
  {
    municipalityName: "Luzern",
    canton: "LU",
    protocolPageUrl: "https://www.stadtluzern.ch/politbusiness/2297179",
    pdfs: [
      {
        title: "Protokoll 9 – Grosser Stadtrat Luzern vom 27. März 2025",
        sourceUrl: "https://www.stadtluzern.ch/_docn/5872306/Protokoll_9_Grosser_Stadtrat_vom_27._Maerz_2025.pdf",
        sessionDate: "2025-03-27",
        type: "protocol",
      },
      {
        title: "Protokoll 7 – Grosser Stadtrat Luzern vom 30. Januar 2025",
        sourceUrl: "https://www.stadtluzern.ch/_docn/5697277/Protokoll_7_Grosser_Stadtrat_vom_30._Januar_2025.pdf",
        sessionDate: "2025-01-30",
        type: "protocol",
      },
      {
        title: "Protokoll 3 – Grosser Stadtrat Luzern vom 24. Oktober 2024",
        sourceUrl: "https://www.stadtluzern.ch/_docn/5489209/Protokoll_3_Grosser_Stadtrat_vom_24._Oktober_2024.pdf",
        sessionDate: "2024-10-24",
        type: "protocol",
      },
    ],
  },
  {
    municipalityName: "St. Gallen",
    canton: "SG",
    protocolPageUrl: "https://www.stadt.sg.ch/home/verwaltung-politik/demokratie-politik/stadtparlament/sitzungen.html",
    pdfs: [
      {
        title: "Stadtparlament St. Gallen – Sitzungsindex 2025–2028",
        sourceUrl: "https://www.stadt.sg.ch/home/verwaltung-politik/demokratie-politik/stadtparlament/sitzungen.html",
        sessionDate: "2025-01-01",
        type: "protocol",
      },
    ],
  },
  {
    municipalityName: "Lugano",
    canton: "TI",
    protocolPageUrl: "https://www.lugano.ch/consiglio-comunale/Calendario-sedute/",
    pdfs: [
      {
        title: "Verbale Consiglio Comunale di Lugano del 26 marzo 2024",
        sourceUrl: "https://www.lugano.ch/downloadCc?name=Verbale+Consiglio+Comunale+del+26+marzo+2024+-+web.pdf&unid=BE581D0A1B6EAB55C1258AED0030B6DA&type=verbale",
        sessionDate: "2024-03-26",
        type: "protocol",
      },
      {
        title: "Verbale Consiglio Comunale di Lugano del 3 luglio 2023",
        sourceUrl: "https://www.lugano.ch/downloadCc?name=Verbale+Consiglio+Comunale+del+3+luglio+2023+-+web.pdf&unid=E1D5C2B66852AAF4C12589E40026CC71&type=verbale",
        sessionDate: "2023-07-03",
        type: "protocol",
      },
    ],
  },
  {
    municipalityName: "Biel/Bienne",
    canton: "BE",
    protocolPageUrl: "https://www.biel-bienne.ch/de/protokolle.html/752",
    pdfs: [
      {
        title: "Stadtratsprotokoll / Procès-verbal du Conseil de ville – 16.01.2025",
        sourceUrl: "https://www.biel-bienne.ch/public/upload/assets/33775/01_01%20vom%2016.%20Januar%202025_GV.PDF?fp=2",
        sessionDate: "2025-01-16",
        type: "protocol",
      },
      {
        title: "Stadtratsprotokoll / Procès-verbal du Conseil de ville – 22.02.2024",
        sourceUrl: "https://www.biel-bienne.ch/public/upload/assets/27894/03_02%20vom%2022.%20Februar%202024_GV.pdf?fp=1714378696790",
        sessionDate: "2024-02-22",
        type: "protocol",
      },
    ],
  },
  {
    municipalityName: "Thun",
    canton: "BE",
    protocolPageUrl: "https://www.thun.ch/stadtratth",
    pdfs: [
      {
        title: "Protokoll Stadtratssitzung Thun vom 17. Februar 2011",
        sourceUrl: "https://www.thun.ch/_docn/4346746/Protokoll_Stadtratssitzung_vom_17._Februar_2011.pdf",
        sessionDate: "2011-02-17",
        type: "protocol",
      },
      {
        title: "Stadtratsbericht – KG und PS Lerchenfeld, 21. März 2024",
        sourceUrl: "https://www.thun.ch/_docn/5009332/SRB_KG_und_PS_Lerchenfeld_Sanierung_und_Erweiterung.pdf",
        sessionDate: "2024-03-21",
        type: "protocol",
      },
    ],
  },
  {
    municipalityName: "Köniz",
    canton: "BE",
    protocolPageUrl: "https://www.koeniz.ch/politik/gemeindeparlament/dokumente-parlamentssitzungen.page/1461",
    pdfs: [
      {
        title: "Protokoll Parlamentssitzung Köniz vom 5. Mai 2025",
        sourceUrl: "https://www.koeniz.ch/public/upload/assets/23094/2025-05-05_Protokoll-Parlament.pdf?fp=1",
        sessionDate: "2025-05-05",
        type: "protocol",
      },
      {
        title: "Protokoll Parlamentssitzung Köniz vom 26. August 2024",
        sourceUrl: "https://www.koeniz.ch/public/upload/assets/22421/2024-08-26_Protokoll-Parlament.pdf?fp=1",
        sessionDate: "2024-08-26",
        type: "protocol",
      },
    ],
  },
  {
    municipalityName: "La Chaux-de-Fonds",
    canton: "NE",
    protocolPageUrl: "https://www.chaux-de-fonds.ch/autorites/conseil-general",
    pdfs: [
      {
        title: "Procès-verbal No 37 – Conseil général, 30 mai 2024",
        sourceUrl: "https://www.chaux-de-fonds.ch/autorites/conseil-general/Documents/seances_CG/2024/20240530/PVCG_N37_Mai_2024.pdf",
        sessionDate: "2024-05-30",
        type: "protocol",
      },
      {
        title: "Procès-verbal No 33 – Conseil général, 14 décembre 2023",
        sourceUrl: "https://www.chaux-de-fonds.ch/autorites/conseil-general/Documents/seances_CG/2023/20231214/PVCG_N33_decembre_2023.pdf",
        sessionDate: "2023-12-14",
        type: "protocol",
      },
    ],
  },
  {
    municipalityName: "Schaffhausen",
    canton: "SH",
    protocolPageUrl: "https://www.stadt-schaffhausen.ch/sitzungenlegislative",
    pdfs: [
      {
        title: "Protokoll Grosser Stadtrat Schaffhausen, Sitzung 5/2025, 18. März 2025",
        sourceUrl: "https://www.stadt-schaffhausen.ch/_docn/5714011/5_Protokoll_Rat5_18_03_2025.pdf",
        sessionDate: "2025-03-18",
        type: "protocol",
      },
      {
        title: "Protokoll Grosser Stadtrat Schaffhausen, Sitzung 15/16, 29. Oktober 2024",
        sourceUrl: "https://www.stadt-schaffhausen.ch/_docn/5523700/15_16_ProtokollRat15_16_29_10_2024.pdf",
        sessionDate: "2024-10-29",
        type: "protocol",
      },
    ],
  },
  {
    municipalityName: "Fribourg",
    canton: "FR",
    protocolPageUrl: "https://www.ville-fribourg.ch/conseil-general/proces-verbaux",
    pdfs: [
      {
        title: "Procès-verbal no 21a – Conseil général Fribourg, 11 décembre 2023",
        sourceUrl: "https://www.ville-fribourg.ch/sites/default/files/inline-files/231211%20PVCG_sans%20signatures.pdf",
        sessionDate: "2023-12-11",
        type: "protocol",
      },
      {
        title: "Procès-verbal no 20 – Conseil général Fribourg, 30 octobre 2023",
        sourceUrl: "https://www.ville-fribourg.ch/sites/default/files/inline-files/231030%20PVCG_sans%20signatures_1.pdf",
        sessionDate: "2023-10-30",
        type: "protocol",
      },
    ],
  },
  {
    municipalityName: "Chur",
    canton: "GR",
    protocolPageUrl: "https://www.chur.ch/protokolle",
    pdfs: [
      {
        title: "Beschlüsse des Gemeinderates Chur (Amtsblatt)",
        sourceUrl: "https://www.chur.ch/_docn/5508244/GR_Beschluesse_Amtsblatt.pdf",
        sessionDate: "2024-11-13",
        type: "protocol",
      },
    ],
  },
  {
    municipalityName: "Vernier",
    canton: "GE",
    protocolPageUrl: "https://www.vernier.ch/administration-et-autorites/vie-politique/conseil-municipal",
    pdfs: [
      {
        title: "Procès-verbal du Conseil municipal de Vernier, 23 janvier 2024",
        sourceUrl: "https://www.vernier.ch/sites/default/files/council-documents/2024-03/CM%202024%2001%2023%20-%2035%20PV%20Acc.pdf",
        sessionDate: "2024-01-23",
        type: "protocol",
      },
      {
        title: "Procès-verbal du Conseil municipal de Vernier, 14 novembre 2023",
        sourceUrl: "https://www.vernier.ch/sites/default/files/council-documents/2023-12/CM%202023%2011%2014%20-%2033%20PV%20Acc.pdf",
        sessionDate: "2023-11-14",
        type: "protocol",
      },
    ],
  },
  {
    municipalityName: "Neuchâtel",
    canton: "NE",
    protocolPageUrl: "https://www.neuchatelville.ch/votre-commune/conseil-general/proces-verbaux",
    pdfs: [
      {
        title: "Procès-verbal 8e séance – Conseil général Neuchâtel, 10 mars 2025",
        sourceUrl: "https://www.neuchatelville.ch/fileadmin/sites/ne_ville/fichiers/votre_commune/CG_NEO/CG_NEO_pv/08_-_10_mars_2025.pdf",
        sessionDate: "2025-03-10",
        type: "protocol",
      },
      {
        title: "Procès-verbal 6e séance – Conseil général Neuchâtel, 13 janvier 2025",
        sourceUrl: "https://www.neuchatelville.ch/fileadmin/sites/ne_ville/fichiers/votre_commune/CG_NEO/CG_NEO_pv/06_-_13_janvier_2025.pdf",
        sessionDate: "2025-01-13",
        type: "protocol",
      },
    ],
  },
  {
    municipalityName: "Uster",
    canton: "ZH",
    protocolPageUrl: "https://www.uster.ch/sitzung",
    pdfs: [
      {
        title: "Protokoll 30. Sitzung Gemeinderat Uster vom 10. Februar 2025",
        sourceUrl: "https://www.uster.ch/_docn/5547184/Protokoll_GR_20250210.pdf",
        sessionDate: "2025-02-10",
        type: "protocol",
      },
      {
        title: "Protokoll 10. Sitzung Gemeinderat Uster vom 20. März 2023",
        sourceUrl: "https://www.uster.ch/_docn/4378423/Protokoll_GR_20230320.pdf",
        sessionDate: "2023-03-20",
        type: "protocol",
      },
    ],
  },
  {
    municipalityName: "Sion",
    canton: "VS",
    protocolPageUrl: "https://www.sion.ch/plenums/5132959",
    pdfs: [
      {
        title: "Procès-verbal – Conseil général de Sion, 11 mars 2025",
        sourceUrl: "https://www.sion.ch/_docn/5843848/P20250311_Proc%C3%A8s-verbal_du_Conseil_g%C3%A9n%C3%A9ral.pdf",
        sessionDate: "2025-03-11",
        type: "protocol",
      },
      {
        title: "Procès-verbal – Conseil général de Sion, 18 juin 2024",
        sourceUrl: "https://www.sion.ch/_docn/5327881/P20240618_Proc%C3%A8s_Verbal_S%C3%A9ance_CG.pdf",
        sessionDate: "2024-06-18",
        type: "protocol",
      },
    ],
  },
];

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  const metadataOnly = process.argv.includes("--metadata-only");

  if (dryRun) console.log("=== DRY RUN ===\n");
  if (metadataOnly) console.log("=== METADATA ONLY (no blob uploads) ===\n");

  const sql = neon(process.env.DATABASE_URL!);
  const db = drizzle({ client: sql });

  let totalInserted = 0;

  for (const entry of TOP_20) {
    console.log(`\n--- ${entry.municipalityName} (${entry.canton}) ---`);

    // Look up municipality by name
    const [muni] = await db
      .select({ id: municipalities.id })
      .from(municipalities)
      .where(ilike(municipalities.name, entry.municipalityName));

    if (!muni) {
      console.log(`  ✗ Municipality "${entry.municipalityName}" not found in DB, skipping`);
      continue;
    }

    console.log(`  Municipality ID: ${muni.id}`);

    // Update website URL if not set
    await db
      .update(municipalities)
      .set({ websiteUrl: entry.protocolPageUrl })
      .where(eq(municipalities.id, muni.id));

    for (const pdf of entry.pdfs) {
      console.log(`  [${pdf.type}] ${pdf.title}`);

      const record: NewDocument = {
        municipalityId: muni.id,
        sourceUrl: pdf.sourceUrl,
        title: pdf.title,
        type: pdf.type,
        sessionDate: new Date(pdf.sessionDate),
        sessionTitle: pdf.title,
      };

      if (!dryRun) {
        const insertResult = await db
          .insert(documents)
          .values(record)
          .onConflictDoNothing();

        if (insertResult.rowCount && insertResult.rowCount > 0) {
          totalInserted++;
          console.log(`    → inserted`);
        } else {
          console.log(`    → already exists, skipped`);
        }
      } else {
        console.log(`    → would insert`);
      }
    }
  }

  console.log(
    `\n${dryRun ? "Dry run complete." : `Done. ${totalInserted} documents inserted.`}`,
  );
}

main().catch((err) => {
  console.error("Seeding failed:", err);
  process.exit(1);
});
